version: "2"
prepare:
  fetch:
    - url: "https://raw.githubusercontent.com/thoughtworks/metricating-api/master/.codeclimate.yml"
checks:
  checks:
  argument-count:
    enabled: true
    config:
      threshold: 4
  complex-logic:
    enabled: true
    config:
      threshold: 4
  file-lines:
    enabled: true
    config:
      threshold: 250
  method-complexity:
    enabled: true
    config:
      threshold: 5
  method-count:
    enabled: true
    config:
      threshold: 20
  method-lines:
    enabled: true
    config:
      threshold: 25
  nested-control-flow:
    enabled: true
    config:
      threshold: 4
  return-statements:
    enabled: true
    config:
      threshold: 4
  similar-code:
    enabled: true
    config:
      threshold: #language-specific defaults. overrides affect all languages.
  identical-code:
    enabled: true
    config:
      threshold: #language-specific defaults. overrides affect all languages.
plugins:
  nodesecurity:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          patterns:
            - "!**/*test.js"
exclude_patterns:
  - "dist/"
  - "**/node_modules/"
  - "**/vendor/"
  - "**/*.d.ts"